### ISSUE TITLE
Error loading accounts

### ISSUE THREAD

**Issue by ysilvela** [mgufrone/cpanel-php#33]
GuzzleHttp\Ring\Exception\RingException: cURL error 3: in /home/bastify/public_html/clientarea/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127
Stack trace:
#0 /home/bastify/public_html/clientarea/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(91): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Array, Array, Array)
#1 /home/bastify/public_html/clientarea/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(96): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Array, Array, Array, Array, Resource id #501)
#2 /home/bastify/public_html/clientarea/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(68): GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray(Array)
#3 /home/bastify/public_html/clientarea/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(54): GuzzleHttp\Ring\Client\CurlHandler->__invoke(Array)
#4 /home/bastify/public_html/clientarea/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(30): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array)
#5 /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/RequestFsm.php(129): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array)
#6 /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#7 /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/Client.php(150): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#8 /home/bastify/public_html/clientarea/vendor/whmapi/src/Gufy/CpanelPhp/Cpanel.php(349): GuzzleHttp\Client->post('/json-api/lista...', Array)
#9 /home/bastify/public_html/clientarea/vendor/whmapi/src/Gufy/CpanelPhp/Cpanel.php(105): Gufy\CpanelPhp\Cpanel->runQuery('listaccts', Array)
#10 /home/bastify/public_html/clientarea/dedicated_list.php(44): Gufy\CpanelPhp\Cpanel->__call('listaccts', Array)
#11 {main}
Next GuzzleHttp\Exception\RequestException: cURL error 3: in /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:51
Stack trace:
#0 /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/RequestFsm.php(103): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
#1 /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#2 /home/bastify/public_html/clientarea/vendor/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#3 /home/bastify/public_html/clientarea/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#4 /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#5 /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#6 /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#7 /home/bastify/public_html/clientarea/vendor/guzzlehttp/guzzle/src/Client.php(150): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#8 /home/bastify/public_html/clientarea/vendor/whmapi/src/Gufy/CpanelPhp/Cpanel.php(349): GuzzleHttp\Client->post('/json-api/lista...', Array)
#9 /home/bastify/public_html/clientarea/vendor/whmapi/src/Gufy/CpanelPhp/Cpanel.php(105): Gufy\CpanelPhp\Cpanel->runQuery('listaccts', Array)
#10 /home/bastify/public_html/clientarea/dedicated_list.php(44): Gufy\CpanelPhp\Cpanel->__call('listaccts', Array)
#11 {main}

**Comment by crossworth** [comment]
The url provided is probably wrong.

cURL error 3 is CURLE_URL_MALFORMAT, The URL was not properly formatted.

http://curl.haxx.se/libcurl/c/libcurl-errors.html
